apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- env.yaml

images:
- name: hferentschik/hello
  newName: hferentschik/hello
  newTag: "latest"
